name: Reusable Workflow

on:
  workflow_call:
    inputs:
      BUILD_UDC:
        required: true
        type: string
      BUILD_VIC:
        required: true
        type: string

jobs:
  print-envs:
    runs-on: ubuntu-latest
    env:
      BUILD_UDC: ${{ inputs.BUILD_UDC }}
      BUILD_VIC: ${{ inputs.BUILD_VIC }}
    steps:
      - name: Show passed environment variables
        run: |
          echo "BUILD_UDC: $BUILD_UDC"
          echo "BUILD_VIC: $BUILD_VIC"
